### ISSUE TITLE
Installation and documentation

### ISSUE THREAD

**Issue by pipnstall** [PKenkel/OUTDOOR#6]
Hello,

my name is Pietro. I would be interested in using/improving OUTDOOR as my research topic is superstructure optimization of biorefinery. I tried to install it through pip install outdoor in Anaconda Promt but I get the following error:

ERROR: Could not find a version that satisfies the requirement outdoor (from versions: none)
ERROR: No matching distribution found for outdoor

Furthermore, is it possible to get more detailed documentation than the one found in the repository?

Thank you very much in advance!
Pietro

**Comment by PKenkel** [comment]
Hey Pietro,
I am very sorry for the inconvenience, but also happy to hear that you are interested in the tool.
Right now it is not possible to install it using the pip / condo install command. 
I am developing it as work of my PhD and didn't get to the point to make it "install-ready". 
However, what you can do is clone the repository. Here I would advise the dev-branch, due to the fact that some new features are implemented and the version should be operational. 
When you cloned the repository, there is also an example excel-file for data input as well as  a python script which loads the outdoor files from the folder and runs the example. This could be a good starting point. 

About the documentation, I am sorry to say that to this point there is not much more available. I started to set up a readthedocs page but due to a lot of other duties in my PhD I had to neglect somewhat. 

I am thankful for your comment though, and I will try to get an installable file, merge the dev and master branch, and take up the documentation part as well, as soon as possible (I am on easter vacation right now, so this will probably take 1-2 weeks) .

I hope I could help you somewhat, if you get other errors or questions feel free to ask again.

Best regards,
Philipp

**Comment by pipnstall** [comment]
Hi Philipp,

thank you very much for your answer! I am also a PhD student, right now I amstill at the beginning of the research project. Don't worry, your code is already very helpful for me as I am convinced it is a very valuable benchmark:)

As you suggested I cloned the dev-branch of the repository and run the TestCase. The console first showed the following error:


  File "C:Documents\GitHub\OUTDOOR-dev/src\outdoor\outdoor_core\Block_SuperstructureModel.py", line 950, in TestRule
    return self.Y[8000] == 1#original 8000

  File "C:\Anaconda3\lib\site-packages\pyomo\core\base\indexed_component.py", line 412, in __getitem__
    validated_index = self._validate_index(index)

  File "C:Anaconda3\lib\site-packages\pyomo\core\base\indexed_component.py", line 571, in _validate_index
    raise KeyError(KeyError: "Index '8000' is not valid for indexed component 'Y'"

I solved the error by changing the integer values in square brakets at lines 949-960 of Block_SuperstructureModel.py 
However, I got this other problem still by running TestCase:

  File "C:Documents\GitHub\OUTDOOR-dev/src\outdoor\outdoor_core\Block_Processing.py", line 8, in searchTechnologies
    if value(Instance.Y[i]) == 0:

  File "pyomo\core\expr\numvalue.pyx", line 246, in pyomo.core.expr.numvalue.value

  File "pyomo\core\expr\numvalue.pyx", line 233, in pyomo.core.expr.numvalue.value

ValueError: No value for uninitialized NumericValue object ModelInstance.Y[6000]

It seems to me that the problem still lays in the values at lines 949-960 of Block_SuperstructureModel.py as the answer to this Stackoverflow post might hint (https://stackoverflow.com/questions/64669576/no-value-for-uninitialized-numericvalue-object-for-a-variablet-pyomo). So, my question is: Do you know some values for lines 949-960 of Block_SuperstructureModel.py that allow to solve the TestCase?

Thank you very much and please apologize the long message!
Pietro

**Comment by PKenkel** [comment]
Hello Pietro,
as you already realized the lines  948 - 980. in Block_SuperstructureModel.py can be deactivated, normally I also always did this but I maybe I forgot it the last time. They are test-constraints which I used to fix the usage of other unit-operations in a bigger example which I had, so they not necessary for the example case. 

About the second error. Normally when 
"ValueError: No value for uninitialized NumericValue object ModelInstance.Y[6000]" 

is the error message this means that the problem is not solved or infeasible, at least that's what  experienced. 
There can be a couple of reasons for this. First of all it is important that you use the right solver, and also that you have it installed. Here gurobi or culex are a good choice. Coin OR-cbc should also work for such a small example but I experienced some issues with this solver sometimes. 

If you are sure that your solver is installed correctly and working, and the problem is really with the example and code, please let me know. In this case I will check in detail with the code again, maybe there is an issue in the newest version. 

Best regards and no problem about the message I am happy to see some interest in my work,
Philipp

**Comment by pipnstall** [comment]
Hello Philipp,
the code is now running! The solver was not properly installed and I used
glpk just for the purpose of running the code.

Thank you so much!
Pietro

P.S.: This might be useful for other people reading this message and are
new to the use of pyomo. Optimization solvers need to be extra installed
and one needs to make sure that while compiling the code of a pyomo
optimization problem the solver is accessed. I solved the issue by reading
this post:
https://stackoverflow.com/questions/41346647/spyder-does-not-find-glpsol
